import type { Metadata } from 'next';
import './globals.css';
import 'react-photo-view/dist/react-photo-view.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-harmonia'>{children}</body>
    </html>
  );
}
